In [1]:
import numpy as np
import pandas as pd


In [3]:
Dict1={
       "name":['harry', 'rohan', 'akash', 'shubh'],
   "Age":[18, 20, 19, 22],
   "city":['raipur', 'kolkata', 'bareilly', 'agra']
}

In [5]:
df=pd.DataFrame(Dict1)

In [6]:
df

name  Age      city
0  harry   18    raipur
1  rohan   20   kolkata
2  akash   19  bareilly
3  shubh   22      agra

In [7]:
import math

In [8]:
a=16
print(math.sqrt(a))

4.0


In [10]:
print(math.pow(a,3))

4096.0


In [13]:
z=16*math.pi


In [14]:
z

50.26548245743669

In [15]:
x1=True
x2=False

print(x1 and x2)
print(x1 or x2)
print(x1 and not x2)



False
True
True


In [16]:
s1 = "String"

print(s1[2:])

ring


In [17]:
print(len(s1))

6


In [20]:
print("Length of String is :", len (s1))

Length of String is : 6


In [22]:
print(s1.upper())

STRING


In [23]:
s2 = "This is a Game"

In [27]:
words = s2.split('4')

In [29]:
print(words[0])

This is a Game


In [32]:
print(s2.replace('is','was'))

print(s2.find('a'))

Thwas was a Game
8


In [8]:
list1 =[1, 3, 4,  5, 7]

In [9]:
print(list1)

[1, 3, 4, 5, 7]


In [10]:
print(sum(list1))

20


In [13]:
list2= list(range(0,16,2))
print(list2)

[0, 2, 4, 6, 8, 10, 12, 14]


In [15]:
list1.append(11) 
print(list1)

[1, 3, 4, 5, 7, 11, 11]


In [16]:
print(list1.pop())            
print(list1)

11
[1, 3, 4, 5, 7, 11]


In [17]:
print(list1 + [11,13,15]) 

[1, 3, 4, 5, 7, 11, 11, 13, 15]


In [18]:
print(list1 * 3) 

[1, 3, 4, 5, 7, 11, 1, 3, 4, 5, 7, 11, 1, 3, 4, 5, 7, 11]


In [19]:
list1.sort(reverse=True)      
print(list1)

[11, 7, 5, 4, 3, 1]


In [20]:
list3 = ['this', 'is', 'a', 'program']
print(list3)
print(type(list3))

print("list" in list3)         
print(list3[2])               
print(list3[:2])                
print(list3[2:])                
list3.append("too")            
separator = " "
print(separator.join(list3))    

list3.remove("is")            
print(list3)

['this', 'is', 'a', 'program']
<class 'list'>
False
a
['this', 'is']
['a', 'program']
this is a program too
['this', 'a', 'program', 'too']


In [21]:
x = 32

if x % 2 == 0:
    print("x =", x, "is even")
else:
    print("x =", x, "is odd")

if x > 0:
    print("x =", x, "is positive")
elif x < 0:
    print("x =", x, "is negative")
else:
    print("x =", x, "is neither positive nor negative")

x = 32 is even
x = 32 is positive


In [22]:
mylist = list(range(-10,10))
print(mylist)

i = 0
while (mylist[i] < 0):
    i = i + 1
    
print("First non-negative number:", mylist[i])

[-10, -9, -8, -7, -6, -5, -4, -3, -2, -1, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
First non-negative number: 0


In [1]:
import numpy as np

Arr = np.array([1,5,8,6,3,7,8,4,6])   
print(Arr)


[1 5 8 6 3 7 8 4 6]


In [2]:
print("#Dimensions =", Arr.ndim)


#Dimensions = 1


In [3]:
print("Dimension =", Arr.shape)


Dimension = (9,)


In [4]:
print("Size =", Arr.size)


Size = 9


In [5]:
print("Array type =", Arr.dtype, '\n')

Array type = int32 



In [6]:
Arr2 = np.array([[1,2],[3,4],[5,6],[7,8]])
print(Arr2)
print("#Dimensions =", Arr2.ndim)


[[1 2]
 [3 4]
 [5 6]
 [7 8]]
#Dimensions = 2


In [7]:
print("Dimension =", Arr2.shape)
print("Size =", Arr2.size)


Dimension = (4, 2)
Size = 8


In [8]:
print("Array type =", Arr2.dtype, '\n')

Array type = int32 



In [9]:
arr3 = np.array([(5,'a',6.0),(2,'b',3.5)])  
print(arr3)


[['5' 'a' '6.0']
 ['2' 'b' '3.5']]


In [10]:
print("#Dimensions =", arr3.ndim)
print("Dimension =", arr3.shape)


#Dimensions = 2
Dimension = (2, 3)


In [11]:
print("Size =", arr3.size)

Size = 6


In [12]:
print(np.random.rand(5))   

[0.13257212 0.04898922 0.16611711 0.70064221 0.37926132]


In [13]:
print(np.random.randn(5)) 

[ 0.56944812  0.74341708  1.09553239 -0.36257579  1.37998288]


In [14]:
print(np.arange(-20,10,2))

[-20 -18 -16 -14 -12 -10  -8  -6  -4  -2   0   2   4   6   8]


In [18]:
print(np.arange(16).reshape(4,4))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [19]:
print(np.zeros((2,3))) 

[[0. 0. 0.]
 [0. 0. 0.]]


In [20]:
x = np.array([8,4,6,9,3,4])

print('x =', x)


x = [8 4 6 9 3 4]


In [21]:
print('x + 1 =', x + 1)      
print('x - 1 =', x - 1)      

x + 1 = [ 9  5  7 10  4  5]
x - 1 = [7 3 5 8 2 3]


In [22]:
print('x * 2 =', x * 2)      
print('x // 2 =', x // 2)     
print('x ** 2 =', x ** 2)     
print('x % 2 =', x % 2)       
print('1 / x =', 1 / x) 

x * 2 = [16  8 12 18  6  8]
x // 2 = [4 2 3 4 1 2]
x ** 2 = [64 16 36 81  9 16]
x % 2 = [0 0 0 1 1 0]
1 / x = [0.125      0.25       0.16666667 0.11111111 0.33333333 0.25      ]


In [23]:
x = np.arange(-5,5)
print('Before: x =', x)

Before: x = [-5 -4 -3 -2 -1  0  1  2  3  4]


In [24]:
y = x[3:5]     
print('        y =', y)
y[:] = 1000   
print('After : y =', y)
print('        x =', x, '\n')

        y = [-2 -1]
After : y = [1000 1000]
        x = [  -5   -4   -3 1000 1000    0    1    2    3    4] 



In [25]:
z = x[3:5].copy()  
print('Before: x =', x)
print('        z =', z)


Before: x = [  -5   -4   -3 1000 1000    0    1    2    3    4]
        z = [1000 1000]


In [27]:
z[:] = 500           # modifying the value of z will not affect x
print('After : z =', z)
print('        x =', x)

After : z = [500 500]
        x = [  -5   -4   -3 1000 1000    0    1    2    3    4]


In [29]:
mylist = [[1,2,3,4],[5,6,7,8],[9,10,11,12]]  # a 2-dim list
print('mylist =', mylist)

mylist = [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]


In [30]:
y = np.array([-1.4, 0.4, -3.2, 2.5, 3.4])    
print('y =', y, '\n')

y = [-1.4  0.4 -3.2  2.5  3.4] 



In [31]:
X = np.random.randn(2,3)                         # create a 2 x 3 random matrix
print('X =\n', X, '\n')


X =
 [[-1.53242414 -1.42342474 -1.73345658]
 [-1.21986073  1.23941715  2.24924956]] 



In [32]:
print('Transpose of X, X.T =\n', X.T, '\n') 

Transpose of X, X.T =
 [[-1.53242414 -1.21986073]
 [-1.42342474  1.23941715]
 [-1.73345658  2.24924956]] 



In [33]:
from pandas import Series

s = Series([3.1, 2.4, -1.7, 0.2, -2.9, 4.5])  
print('Series, s =\n', s, '\n')

Series, s =
 0    3.1
1    2.4
2   -1.7
3    0.2
4   -2.9
5    4.5
dtype: float64 



In [34]:
print('s.values =', s.values)  

s.values = [ 3.1  2.4 -1.7  0.2 -2.9  4.5]


In [35]:
print('s.index =', s.index)      
print('s.dtype =', s.dtype) 

s.index = RangeIndex(start=0, stop=6, step=1)
s.dtype = float64


In [36]:
ser1= Series([1.2,2.5,-2.2,3.1,-0.8,-3.2], 
            index = ['Jan 1','Jan 2','Jan 3','Jan 4','Jan 5','Jan 6',])
print('Series s3 =\n', ser1, '\n')

Series s3 =
 Jan 1    1.2
Jan 2    2.5
Jan 3   -2.2
Jan 4    3.1
Jan 5   -0.8
Jan 6   -3.2
dtype: float64 



In [37]:
print('s.index =', ser1.index)      
print('s.dtype =', ser1.dtype) 

s.index = Index(['Jan 1', 'Jan 2', 'Jan 3', 'Jan 4', 'Jan 5', 'Jan 6'], dtype='object')
s.dtype = float64


In [39]:
ser1['Jan 7'] = np.nan
print('Series s3 =\n', ser1, '\n')

Series s3 =
 Jan 1    1.2
Jan 2    2.5
Jan 3   -2.2
Jan 4    3.1
Jan 5   -0.8
Jan 6   -3.2
Jan 7    NaN
dtype: float64 



In [40]:
s['Jan 7'] = np.nan
print(s)

0        3.1
1        2.4
2       -1.7
3        0.2
4       -2.9
5        4.5
Jan 7    NaN
dtype: float64


In [41]:
print(ser1[ser1 > 0]) 

Jan 1    1.2
Jan 2    2.5
Jan 4    3.1
dtype: float64


In [42]:
print('ser1 / 4 =\n', ser1 / 4)   

ser1 / 4 =
 Jan 1    0.300
Jan 2    0.625
Jan 3   -0.550
Jan 4    0.775
Jan 5   -0.200
Jan 6   -0.800
Jan 7      NaN
dtype: float64


In [49]:
from pandas import DataFrame

raj = [(2011,45.1,32.4),(2012,42.4,34.5),(2013,47.2,39.2),
              (2014,44.2,31.4),(2015,39.9,29.8),(2016,41.5,36.7)]
columnNames = ['year','temp','precip']
weatherData = DataFrame(raj, columns=columnNames ) 
weatherData

year  temp  precip
0  2011  45.1    32.4
1  2012  42.4    34.5
2  2013  47.2    39.2
3  2014  44.2    31.4
4  2015  39.9    29.8
5  2016  41.5    36.7